### ISSUE TITLE
API og epostbekreftelse

### ISSUE THREAD

**Issue by bjornreppen** [kartverket/Geonorge.NedlastingAPI#6]
Forsøker å automatisere nedlasting fra GEONORGE ved hjelp av APIet.   Ville foretrukket å bare kunne pekt på en URL, men ser ut som de fleste etater har giftet seg med proprietær programvare som på en eller annen måte gjør det vanskelig å publisere filer på en statisk URL?  Kudos til for eksempel NIBIO for å ha gjort ting enkelt for brukere

Utsatte i det lengste, men til slutt brøt meg på.  Startet med Miljødirektoratet sine Naturvernområder på https://kartkatalog.geonorge.no/metadata/miljodirektoratet/naturvernomrader/5857ec0a-8d2c-4cd8-baa2-0dc54ae213b4  ... da denne ikke tilbys på WFS, eller som fil på en statisk URL det kan lastes fra.

Bestilling gikk relativt greit å få til (prøvde først å lese docs, men etterhvert gikk jeg lei og kopierte heller JSON payload fra handlekurv-submit på GEONORGE.

Det store spørsmålet er: Hvordan får man tak i nedlastingslenken som først er tilgjengelig når ordren er ferdigprosessert?  Jeg har så langt ikke klart å få ut noen oppdatert status fra APIet, finner lenke så langt bare i en epost?  Hvordan forteller man evt. APIet at man ikke ønsker å få bekreftelse på epost, men via APIet?  Er dette avhengig av oppsettet hos dataleverandøren?

JSON payload som jeg poster til `https://nedlasting.geonorge.no/api/order`
```json
{
  "email": "nospam@gmail.com",
  "usageGroup": "samarbeidspartner",
  "softwareClient": "Kartkatalogen",
  "softwareClientVersion": "11.0.2004",
  "orderLines": [
    {
      "metadataUuid": "5857ec0a-8d2c-4cd8-baa2-0dc54ae213b4",
      "areas": [
        {
          "code": "norgemedsvalbard",
          "name": "Hele landet med svalbard",
          "type": "landsdekkende"
        }
      ],
      "projections": [
        {
          "code": "25833",
          "name": "EUREF89 UTM sone 33, 2d",
          "codespace": "http://www.opengis.net/def/crs/EPSG/0/25833"
        }
      ],
      "formats": [{ "code": "", "name": "GeoJSON", "type": "" }],
      "usagePurpose": ["kunnskapkompetanse"]
    }
  ]
}
```

**Comment by dagolav** [comment]
Hei!
Du må poste til miljødirektoratet sin implementasjon som er oppgitt i metadata xml:
https://api.miljodirektoratet.no/v1/capabilities?uuid=5857ec0a-8d2c-4cd8-baa2-0dc54ae213b4
https://api.miljodirektoratet.no/v1/order?uuid=5857ec0a-8d2c-4cd8-baa2-0dc54ae213b4
Men det ser vel ikke ut som de gir noen respons annet enn http 200 ok, så siden deliveryNotificationByEmail: true regner jeg med at det ikke er noen annen mulighet, men hør eventuelt med Miljødirektoratet.
Se eksempel her på forespørsel/respons flyt:
https://nedlasting.geonorge.no/help/documentation

**Comment by bjornreppen** [comment]
Veldig oppklarende!  Tusen takk!
